name: CI

# This workflow run tests and build for each push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version

      - name: Build
        run: cargo build --verbose
